name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker images
        run: |
          docker build -t frontend ./front
          docker build -t backend ./back

      - name: Deploy to Hetzner
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          VM_IP: ${{ secrets.VM_IP }}
        run: |
          scp docker-compose.yml user@${{ env.VM_IP }}:/home/user/testtwenty/
          ssh user@${{ env.VM_IP }} 'cd /home/user/testtwenty && docker-compose up -d'
